//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.ProductsOrders = new HashSet<ProductsOrders>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ProductsOrders> ProductsOrders { get; set; }
    }
}
